"""empty message

Revision ID: 3f4fa12762f6
Revises: 
Create Date: 2025-12-28 15:45:19.691726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4fa12762f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_no', sa.String(length=50), nullable=False),
    sa.Column('quotation_date', sa.Date(), nullable=False),
    sa.Column('bill_to', sa.String(length=200), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=True),
    sa.Column('contact_no', sa.String(length=20), nullable=True),
    sa.Column('customer_gstin', sa.String(length=20), nullable=True),
    sa.Column('estimate_no', sa.String(length=50), nullable=True),
    sa.Column('estimate_date', sa.Date(), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('company_description', sa.Text(), nullable=True),
    sa.Column('company_phone', sa.String(length=20), nullable=True),
    sa.Column('company_gstin', sa.String(length=20), nullable=True),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('company_branch', sa.String(length=100), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('cgst', sa.Float(), nullable=True),
    sa.Column('sgst', sa.Float(), nullable=True),
    sa.Column('grand_total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_no')
    )
    op.create_table('quotation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('item_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotation_items')
    op.drop_table('quotations')
    op.drop_table('login')
    # ### end Alembic commands ###
